---
title: "Untitled"
format: html
---

# Load Packages
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, stringr, readxl, data.table, gdata)
```

# Question 1
```{r}
for (y in 2010:2015) {
  ## Basic contract/plan information
  y=2010
  ma.path=paste0("data/input/monthly-ma-and-pdp-enrollment-by-cpsc/CPSC_Contract_Info_",y,"_01.csv")
  contract.info=read_csv(ma.path,
                         skip=1,
                         col_names = c("contractid","planid","org_type","plan_type",
                                       "partd","snp","eghp","org_name","org_marketing_name",
                                       "plan_name","parent_org","contract_date"),
                         col_types = cols(
                           contractid = col_character(),
                           planid = col_double(),
                           org_type = col_character(),
                           plan_type = col_character(),
                           partd = col_character(),
                           snp = col_character(),
                           eghp = col_character(),
                           org_name = col_character(),
                           org_marketing_name = col_character(),
                           plan_name = col_character(),
                           parent_org = col_character(),
                           contract_date = col_character()
                         ))

  contract.info = contract.info %>%
    group_by(contractid, planid) %>%
    mutate(id_count=row_number())
    
  contract.info = contract.info %>%
    filter(id_count==1) %>%
    select(-id_count)
    
    ## Enrollments per plan
  ma.path=paste0("data/input/monthly-ma-and-pdp-enrollment-by-cpsc/CPSC_Enrollment_Info_",y,"_01.csv")
  enroll.info=read_csv(ma.path,
                       skip=1,
                       col_names = c("contractid","planid","ssa","fips","state","county","enrollment"),
                       col_types = cols(
                       contractid = col_character(),
                       planid = col_double(),
                       ssa = col_double(),
                       fips = col_double(),
                       state = col_character(),
                       county = col_character(),
                       enrollment = col_double()
                       ),na="*")
    

  ## Merge contract info with enrollment info
  plan.data = contract.info %>%
    left_join(enroll.info, by=c("contractid", "planid")) %>%
    mutate(year=y)
    
  ## Fill in missing fips codes (by state and county)
  plan.data = plan.data %>%
    group_by(state, county) %>%
    fill(fips)

  ## Fill in missing plan characteristics by contract and plan id
  plan.data = plan.data %>%
    group_by(contractid, planid) %>%
    fill(plan_type, partd, snp, eghp, plan_name)
  
  ## Fill in missing contract characteristics by contractid
  plan.data = plan.data %>%
    group_by(contractid) %>%
    fill(org_type,org_name,org_marketing_name,parent_org)
    
  ## Collapse from monthly data to yearly
  plan.year = plan.data %>%
    group_by(contractid, planid, fips) %>%
    arrange(contractid, planid, fips) %>%
    rename(avg_enrollment=enrollment)
  
  write_rds(plan.year,paste0("data/output/ma_data_",y,".rds"))
}

full.ma.data <- read_rds("data/output/ma_data_2007.rds")
for (y in 2010:2015) {
  full.ma.data <- rbind(full.ma.data,read_rds(paste0("data/output/ma_data_",y,".rds")))
}

write_rds(full.ma.data,"data/output/full_ma_data.rds")
sapply(paste0("ma_data_", 2010:2015, ".rds"), unlink)

```
```{r}
ma.path.2010a=paste0("data/input/ma-plan-characteristics/2010LandscapeSourceData_MA_12_01_09_A_to_M.csv")
ma.data.2010a=read_csv(ma.path.2010a,
                       skip=5,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","demo_type","contractid",
                                   "planid","segmentid","moop"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         demo_type = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character()
                       ))



ma.path.2010b=paste0("data/input/ma-plan-characteristics/2010LandscapeSourceData_MA_12_01_09_N_to_W.csv")
ma.data.2010b=read_csv(ma.path.2010b,
                       skip=5,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","demo_type","contractid",
                                   "planid","segmentid","moop"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         demo_type = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character()
                       ))
ma.data.2010 = rbind(ma.data.2010a,ma.data.2010b)


macd.path.2010a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2010 Plan Report 09-14-09.xls")
macd.data.2010a=read_xls(macd.path.2010a,
                         range="A5:AC26372",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","partd_rein_demo","partd_rein_demo_type","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))

macd.path.2010b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2010 Plan Report 09-14-09.xls")
macd.data.2010b=read_xls(macd.path.2010b,
                         range="A5:AC31073",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","partd_rein_demo","partd_rein_demo_type","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))
macd.data.2010 = rbind(macd.data.2010a,macd.data.2010b)



## Raw 2011 data
ma.path.2011a=paste0("data/input/ma-plan-characteristics/2011LandscapeSourceData_MA_12_17_10_AtoM.csv")
ma.data.2011a=read_csv(ma.path.2011a,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","free_preventive_care"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         free_preventive_care = col_character()
                       ))


ma.path.2011b=paste0("data/input/ma-plan-characteristics/2011LandscapeSourceData_MA_12_17_10_NtoW.csv")
ma.data.2011b=read_csv(ma.path.2011b,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","free_preventive_care"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         free_preventive_care = col_character()
                       ))
ma.data.2011 = rbind(ma.data.2011a,ma.data.2011b)


macd.path.2011a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2011 Plan Report 09-15-10.xls")
macd.data.2011a=read_xls(macd.path.2011a,
                         range="A5:AA18105",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))

macd.path.2011b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2011 Plan Report 09-15-10.xls")
macd.data.2011b=read_xls(macd.path.2011b,
                         range="A5:AA20402",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))
macd.data.2011 = rbind(macd.data.2011a,macd.data.2011b)





## Raw 2012 data
ma.path.2012a=paste0("data/input/ma-plan-characteristics/2012LandscapeSourceData_MA_3_08_12_AtoM.csv")
ma.data.2012a=read_csv(ma.path.2012a,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))



ma.path.2012b=paste0("data/input/ma-plan-characteristics/2012LandscapeSourceData_MA_3_08_12_NtoW.csv")
ma.data.2012b=read_csv(ma.path.2012b,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))
ma.data.2012 = rbind(ma.data.2012a,ma.data.2012b)


macd.path.2012a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2012 Plan Report 09-08-11.xls")
macd.data.2012a=read_xls(macd.path.2012a,
                         range="A5:AA18521",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))

macd.path.2012b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2012 Plan Report 09-08-11.xls")
macd.data.2012b=read_xls(macd.path.2012b,
                         range="A5:AA21182",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))
macd.data.2012 = rbind(macd.data.2012a,macd.data.2012b)




## Raw 2013 data
ma.path.2013a=paste0("data/input/ma-plan-characteristics/2013LandscapeSource file MA_AtoM 11212012.csv")
ma.data.2013a=read_csv(ma.path.2013a,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))


ma.path.2013b=paste0("data/input/ma-plan-characteristics/2013LandscapeSource file MA_NtoW 11212012.csv")
ma.data.2013b=read_csv(ma.path.2013b,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))

ma.data.2013 = rbind(ma.data.2013a,ma.data.2013b)


macd.path.2013a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2013 Plan Report 04252013v1.xls")
macd.data.2013a=read_xls(macd.path.2013a,
                         range="A5:AA20940",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))

macd.path.2013b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2013 Plan Report 04252013v1.xls")
macd.data.2013b=read_xls(macd.path.2013b,
                         range="A5:AA23812",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))
macd.data.2013 = rbind(macd.data.2013a,macd.data.2013b)



## Raw 2014 data
ma.path.2014a=paste0("data/input/ma-plan-characteristics/2014LandscapeSource file MA_AtoM 05292014.csv")
ma.data.2014a=read_csv(ma.path.2014a,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))


ma.path.2014b=paste0("data/input/ma-plan-characteristics/2014LandscapeSource file MA_NtoW 05292014.csv")
ma.data.2014b=read_csv(ma.path.2014b,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))

ma.data.2014 = rbind(ma.data.2014a,ma.data.2014b)


macd.path.2014a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2014 Plan Report 05292014.xls")
macd.data.2014a=read_xls(macd.path.2014a,range="A5:AA15859",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))

macd.path.2014b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2014 Plan Report 05292014.xls")
macd.data.2014b=read_xls(macd.path.2014b,
                         range="A5:AA20305",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage","gap_coverage_type"))
macd.data.2014 = rbind(macd.data.2014a,macd.data.2014b)



## Raw 2015 data
ma.path.2015a=paste0("data/input/ma-plan-characteristics/2015LandscapeSource file MA_AtoM 11042014.csv")
ma.data.2015a=read_csv(ma.path.2015a,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))

ma.path.2015b=paste0("data/input/ma-plan-characteristics/2015LandscapeSource file MA_NtoW 11042014.csv")
ma.data.2015b=read_csv(ma.path.2015b,
                       skip=6,
                       col_names=c("state","county","org_name","plan_name","plan_type","premium","partd_deductible",
                                   "drug_type","gap_coverage","drug_type_detail","contractid",
                                   "planid","segmentid","moop","star_rating"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         org_name = col_character(),
                         plan_name = col_character(),
                         plan_type = col_character(),
                         premium = col_number(),
                         partd_deductible = col_number(),
                         drug_type = col_character(),
                         gap_coverage = col_character(),
                         drug_type_detail = col_character(),
                         contractid = col_character(),
                         planid = col_double(),
                         segmentid = col_double(),
                         moop = col_character(),
                         star_rating = col_character()
                       ))
ma.data.2015 = rbind(ma.data.2015a,ma.data.2015b)


macd.path.2015a=paste0("data/input/ma-plan-characteristics/Medicare Part D 2015 Plan Report 03182015.xls")
macd.data.2015a=read_xls(macd.path.2015a,
                         range="A5:Z16666",
                         sheet="Alabama to Montana",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage"))

macd.path.2015b=paste0("data/input/ma-plan-characteristics/Medicare Part D 2015 Plan Report 03182015.xls")
macd.data.2015b=read_xls(macd.path.2015b,
                         range="A5:Z17038",
                         sheet="Nebraska to Wyoming",
                         col_names=c("state","county","org_name","plan_name","contractid","planid","segmentid",
                                     "org_type","plan_type","snp","snp_type","benefit_type","below_benchmark",
                                     "national_pdp","premium_partc",
                                     "premium_partd_basic","premium_partd_supp","premium_partd_total",
                                     "pard_assist_full","partd_assist_75","partd_assist_50","partd_assist_25",
                                     "partd_deductible","deductible_exclusions","increase_coverage_limit",
                                     "gap_coverage"))
macd.data.2015 = rbind(macd.data.2015a,macd.data.2015b)


for (y in 2007:2015) {

  ############ CLEAN MA-Only Data #####################
  ma.data=get(paste0("ma.data.",y))
  ma.data = ma.data %>%
    select(contractid, planid, state, county, premium)

  ## Fill in missing plan info (by contract, plan, state, and county)
  ma.data = ma.data %>%
    group_by(contractid, planid, state, county) %>%
    fill(premium)

  ## Remove duplicates
  ma.data = ma.data %>%
    group_by(contractid, planid, state, county) %>%
    mutate(id_count=row_number())
  
  ma.data = ma.data %>%
    filter(id_count==1) %>%
    select(-id_count)

    
  ############ CLEAN MA-PD Data #####################
  macd.data=get(paste0("macd.data.",y))
  macd.data = macd.data %>% 
    select(contractid, planid, state, county, premium_partc, premium_partd_basic, 
           premium_partd_supp, premium_partd_total, partd_deductible) %>%
    mutate(planid=as.numeric(planid))
  
  macd.data = macd.data %>%
    group_by(contractid, planid, state, county) %>%
    fill(premium_partc, premium_partd_basic, premium_partd_supp, premium_partd_total, partd_deductible)
  
  ## Remove duplicates
  macd.data = macd.data %>%
    group_by(contractid, planid, state, county) %>%
    mutate(id_count=row_number())
  
  macd.data = macd.data %>%
    filter(id_count==1) %>%
    select(-id_count)

  ## Merge Part D info to Part C info
  ma.macd.data = ma.data %>%
    full_join(macd.data, by=c("contractid", "planid", "state", "county")) %>%
    mutate(year=y)
  
  if (y==2007) {
    plan.premiums=ma.macd.data
  } else {
    plan.premiums=rbind(plan.premiums,ma.macd.data)
  }  
}

```
```{r}
monthlist_2010=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2011=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2012=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2013=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2014=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2015=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
## Read in monthly files, append to yearly file, fill in missing info, and collapse down to yearly file
for (y in 2006:2015) {
  monthlist=get(paste0("monthlist_",y))
  step=0
  for (m in monthlist) {
    step=step+1
    
    ## Pull service area data by contract/month
    ma.path=paste0("data/input/monthly-ma-contract-service-area/MA_Cnty_SA_",y,"_",m,".csv")
    service.area=read_csv(ma.path,skip=1,
                          col_names=c("contractid","org_name","org_type","plan_type","partial","eghp",
                                      "ssa","fips","county","state","notes"),
                          col_types = cols(
                            contractid = col_character(),
                            org_name = col_character(),
                            org_type = col_character(),
                            plan_type = col_character(),
                            partial = col_logical(),
                            eghp = col_character(),
                            ssa = col_double(),
                            fips = col_double(),
                            county = col_character(),
                            notes = col_character()
                          ), na='*')
    service.area = service.area %>%
      mutate(month=m, year=y)
    if (step==1) {
      service.year=service.area
    } else {
      service.year=rbind(service.year,service.area)
    }
  }
  
  
  ## Fill in missing fips codes (by state and county)
  service.year = service.year %>%
    group_by(state, county) %>%
    fill(fips)

  ## Fill in missing plan type, org info, partial status, and eghp status (by contractid)
  service.year = service.year %>%
    group_by(contractid) %>%
    fill(plan_type, partial, eghp, org_type, org_name)
  

  ## Collapse to yearly data
  service.year = service.year %>%
    group_by(contractid, fips) %>%
    mutate(id_count=row_number())
  
  service.year = service.year %>%
    filter(id_count==1) %>%
    select(-c(id_count,month))

  
  assign(paste("service.area.",y,sep=""),service.year)  
}

contract.service.area=rbind(service.area.2006,service.area.2007,service.area.2008,service.area.2009,service.area.2010,
                            service.area.2011,service.area.2012,service.area.2013,service.area.2014,service.area.2015)
write_rds(contract.service.area,"data/output/contract_service_area.rds")
```
```{r}
monthlist_2010=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2011=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2012=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2013=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2014=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
monthlist_2015=c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")


## Read in monthly files, append to yearly file, fill in missing info, and collapse down to yearly file
for (y in 2008:2015) {
  monthlist=get(paste0("monthlist_",y))
  step=0
  for (m in monthlist) {
    step=step+1
    
    ## Pull market penetration data by contract/month
    ma.path=paste0("data/input/monthly-ma-state-and-county-penetration/State_County_Penetration_MA_",y,"_",m,".csv")
    pene.data=read_csv(ma.path,skip=1,
                       col_names=c("state","county","fips_state","fips_cnty","fips",
                                   "ssa_state","ssa_cnty","ssa","eligibles","enrolled",
                                   "penetration"),
                       col_types = cols(
                         state = col_character(),
                         county = col_character(),
                         fips_state = col_integer(),
                         fips_cnty = col_integer(),
                         fips = col_double(),
                         ssa_state = col_integer(),
                         ssa_cnty = col_integer(),
                         ssa = col_double(),
                         eligibles = col_number(),
                         enrolled = col_number(),
                         penetration = col_number()
                       ), na="*")
    
    ## Add month and year data
    pene.data = pene.data %>%
      mutate(month=m, year=y)
    
    if (step==1) {
      ma.penetration=pene.data
    } else {
      ma.penetration=rbind(ma.penetration,pene.data)
    }
  }
  
  
  ## Fill in missing fips codes (by state and county)
  ma.penetration = ma.penetration %>%
    group_by(state, county) %>%
    fill(fips)

  ## Collapse to yearly data
  ma.penetration = ma.penetration %>%
    group_by(fips,state,county) %>%
    summarize(avg_eligibles=mean(eligibles),sd_eligibles=sd(eligibles),
              min_eligibles=min(eligibles),max_eligibles=max(eligibles),
              first_eligibles=first(eligibles),last_eligibles=last(eligibles),
              avg_enrolled=mean(enrolled),sd_enrolled=sd(enrolled),
              min_enrolled=min(enrolled),max_enrolled=max(enrolled),
              first_enrolled=first(enrolled),last_enrolled=last(enrolled),              
              year=last(year),ssa=first(ssa))
  
  assign(paste0("ma.pene.",y),ma.penetration)  
}

ma.penetration.data=rbind(ma.pene.2008,ma.pene.2009,ma.pene.2010,
                          ma.pene.2011,ma.pene.2012,ma.pene.2013,ma.pene.2014,ma.pene.2015)
write_rds(ma.penetration.data,"data/output/ma_penetration.rds")
```
```{r}

```
